POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "id": 5,
    "nome": "Nunes",
    "email": "nunes@empresa.com.br",
    "senha": "654321"
}

###
GET http://localhost:3333/usuarios